spring:
  application:
    name: gateway
server:
  port: 8080

zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://ec2-18-228-162-7.sa-east-1.compute.amazonaws.com:8761
      strip-prefix: true

hystrix: 
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

