spring:
  application:
    name: gateway
server:
  port: 8080
 
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      serviceId: eureka
      strip-prefix: true

hystrix: 
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

